# Generated by Django 4.2.7 on 2023-12-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("re_ex1", models.CharField(max_length=50)),
                ("re_ex2", models.CharField(max_length=50)),
                ("re_ex3", models.CharField(max_length=50)),
                ("re_fd1", models.CharField(max_length=50)),
                ("re_fd2", models.CharField(max_length=50)),
                ("re_fd3", models.CharField(max_length=50)),
                ("re_tea1", models.CharField(max_length=50)),
                ("re_ac", models.CharField(max_length=50)),
                ("todaycontent", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="TodayContent",
        ),
    ]
