# Generated by Django 3.2.23 on 2023-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_resultfeedback_delete_todaycontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultfeedback',
            name='re_ac',
        ),
        migrations.RemoveField(
            model_name='resultfeedback',
            name='re_ex1',
        ),
        migrations.RemoveField(
            model_name='resultfeedback',
            name='re_ex2',
        ),
        migrations.RemoveField(
            model_name='resultfeedback',
            name='re_ex3',
        ),
        migrations.RemoveField(
            model_name='resultfeedback',
            name='re_fd1',
        ),
        migrations.RemoveField(
            model_name='resultfeedback',
            name='re_fd2',
        ),
        migrations.RemoveField(
            model_name='resultfeedback',
            name='re_fd3',
        ),
        migrations.RemoveField(
            model_name='resultfeedback',
            name='re_tea1',
        ),
        migrations.RemoveField(
            model_name='resultfeedback',
            name='todaycontent',
        ),
        migrations.AddField(
            model_name='resultfeedback',
            name='feedback_ac',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultfeedback',
            name='feedback_fd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultfeedback',
            name='feedback_pd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultfeedback',
            name='feedback_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
