# Generated by Django 3.2.23 on 2023-12-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20231206_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultFeedback',
        ),
    ]
