# Generated by Django 3.2.23 on 2023-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_delete_resultfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='today_feel',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
