# Generated by Django 3.2.23 on 2023-12-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_resultfeedback_body_parts_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfeedback',
            name='body_check_image',
            field=models.ImageField(blank=True, null=True, upload_to='body_check_images/'),
        ),
    ]
